### ISSUE TITLE
@kubb/plugin-zod - `app.getFiles is not a function` error since 4.2.0

### ISSUE THREAD

**Issue by alexander-boehm-syzygy** [kubb-labs/kubb#1944]
### What version of `kubb` is running?

4.2.0

### What kind of platform do you use?

MacOS

### Your `kubb.config.ts` config file?

```typescript
import { defineConfig } from '@kubb/core';
import { pluginOas } from '@kubb/plugin-oas';
import { pluginZod } from '@kubb/plugin-zod';

export default defineConfig(() => {
	return {
		input: {
			path: './api/swagger.yaml',
		},
		output: {
			clean: true,
			extension: { '.ts': '' },
			path: './src/DataSources/Trainings/__generated__',
		},
		plugins: [
			pluginOas(),
			pluginZod({
				dateType: 'stringOffset',
				group: { type: 'tag' },
				inferred: true,
				output: { barrelType: 'propagate', path: './zod' },
				unknownType: 'unknown',
				version: '4',
			}),
		],
	};
});
```

### Swagger/OpenAPI file?

```bash

```

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

```JSON

```

### What steps can reproduce the bug?

When I run `pnpm dlx kubb generate` I get the following error message:

> app.getFiles is not a function (plugin: plugin-zod, hook: buildStart) (plugin: plugin-zod, hook: buildStart)

This is the case in version `4.2.0`. It works fine in older versions up to `4.1.4`. We haven't had any problems in recent months.

### How often does this bug happen?

Every time

### What is the expected behaviour?

It should run the generation.

### Additional information

The complete output:

```console
pnpm dlx kubb generate --config kubb.config.ts

Kubb CLI:                                                                                                                                                                          2:06:02 PM
◐ Loading config                                                    2:06:03 PM
✔ Config loaded(kubb.config.ts)                                    2:06:03 PM
◐ Building ./api/swagger.yaml                                       2:06:03 PM
100% ........................... 2/2 | plugin-oas: buildStart
 ERROR  Build failed ./api/swagger.yaml                             2:06:03 PM


 ╭────────────────────────────────────────────────────────────────────────────────────────────────╮
 │                                                                                                │
 │  Plugins:        2 failed, 2 total                                                             │
 │  Failed:          plugin-oas, plugin-zod                                                       │
 │  Generated:      0 files in 0.391s                                                             │
 │  Output:         /Users/XXX/XXX/__generated__  │
 │                                                                                                │
 ╰────────────────────────────────────────────────────────────────────────────────────────────────╯


[2:06:03 PM]  ERROR  app.getFiles is not a function (plugin: plugin-zod, hook: buildStart) (plugin: plugin-zod, hook: buildStart)

    at EventEmitter.<anonymous> (node_modules/@kubb/core/dist/logger-CsQ2EGpR.js:1019:17)
    at EventEmitter.emit (node:events:519:28)
    at EventEmitter$1.emit (node_modules/@kubb/core/dist/logger-CsQ2EGpR.js:968:17)
    at Object.emit (node_modules/@kubb/core/dist/logger-CsQ2EGpR.js:1032:18)
    at #catcher (node_modules/@kubb/core/dist/index.js:563:15)
    at node_modules/@kubb/core/dist/index.js:377:18
    at Array.forEach (<anonymous>)
    at PluginManager.hookParallel (node_modules/@kubb/core/dist/index.js:374:11)
    at async safeBuild (node_modules/@kubb/core/dist/index.js:657:3)
    at async generate (node_modules/@kubb/cli/dist/generate-Cc3YLh0Y.js:6516:27)

  [cause]: app.getFiles is not a function (plugin: plugin-zod, hook: buildStart)

      at EventEmitter.<anonymous> (node_modules/@kubb/core/dist/logger-CsQ2EGpR.js:1019:17)
      at EventEmitter.emit (node:events:519:28)
      at EventEmitter$1.emit (node_modules/@kubb/core/dist/logger-CsQ2EGpR.js:968:17)
      at Object.emit (node_modules/@kubb/core/dist/logger-CsQ2EGpR.js:1032:18)
      at #catcher (node_modules/@kubb/core/dist/index.js:563:15)
      at node_modules/@kubb/core/dist/index.js:506:18

    [cause]: app.getFiles is not a function

        at Object.schema (node_modules/@kubb/plugin-oas/dist/generators-CC4tK-sV.js:112:15)
        at node_modules/@kubb/plugin-oas/dist/SchemaGenerator-DYOXlswO.js:893:36
        at node_modules/@kubb/plugin-oas/dist/SchemaGenerator-DYOXlswO.js:83:31
        at run (node_modules/@kubb/plugin-oas/dist/SchemaGenerator-DYOXlswO.js:83:56)
```

**Comment by stijnvanhulle** [comment]
@alexander-boehm-syzygy Our package.json had a package with a higher range than before. We update Kubb and will release 4.2.1 later today :)
